version: "3"

services:
  postgres:
    container_name: postgres-dev
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  typesense:
    container_name: typesense-dev
    image: typesense/typesense:0.25.1
    restart: unless-stopped
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_DATA_DIR: "/data"
      TYPESENSE_ENABLE_CORS: "true"
    env_file:
      - .env.development
    volumes:
      - typesense-dev-data:/data
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "apt install curl -y &>/dev/null || curl --silent --fail localhost:8108/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-dev-data:
    name: postgres-dev-data
  typesense-dev-data:
    name: typesense-dev-data

networks:
  app-network:
    name: app-network
