services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    restart: unless-stopped
    ports:
      - 3300:3300
    volumes:
      - web-uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      meilisearch:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    # ports:
    # - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-config.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.5
    restart: unless-stopped
    # ports:
    # - "7700:7700"
    env_file:
      - .env
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 1m30s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  meilisearch-data:
  web-uploads:
