services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    container_name: postgres-dev
    image: postgres:18
    restart: unless-stopped
    volumes:
      - postgres-dev-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  meilisearch:
    container_name: meilisearch-dev
    image: getmeili/meilisearch:v1.5
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: "meilisearch_master_key"
    volumes:
      - meilisearch-dev-data:/meili_data
    network_mode: service:db

volumes:
  postgres-dev-data:
  meilisearch-dev-data:
