import React, { useState } from "react";
import Head from "next/head";
import clsx from "clsx";
import dynamic from "next/dynamic";
import * as Collapsible from "@radix-ui/react-collapsible";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import { Roboto_Flex } from "@next/font/google";

import { getPageList, getPage, deletePage } from "@/utils/queryFunctions";

import Sidebar from "@/components/Sidebar";
import PageList from "@/components/PageList";
import Profile from "@/components/Profile";
import EditorPane from "@/components/EditorPane";
import EditorToolbar from "@/components/EditorToolbar";
import { MdMenu } from "react-icons/md";
import ToolbarButton from "@/components/ToolbarButton";
import { HiChevronDoubleLeft } from "react-icons/hi2";
import { RxHamburgerMenu } from "react-icons/rx";

const NoSSRTiptap = dynamic(() => import("../components/Tiptap"), {
  ssr: false,
});

const roboto = Roboto_Flex({
  subsets: ["latin"],
});

export default function Home() {
  const queryClient = useQueryClient();

  const pageListQuery = useQuery({
    queryKey: ["pageList"],
    queryFn: getPageList,
  });

  const id = pageListQuery.data?.[0].id.toString();

  const pageQuery = useQuery({
    queryKey: ["page", id],
    queryFn: () => getPage(id),
    enabled: !!id,
  });

  const pageDeleteMutation = useMutation({
    mutationFn: deletePage,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["pageList"] });
    },
  });

  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  return (
    <>
      <Head>
        <title>Project Potion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={clsx(roboto.className, "relative h-screen w-screen")}>
        <EditorToolbar setIsOpen={() => setIsSidebarOpen((old) => !old)} />

        {pageListQuery.data && (
          <div className="flex h-screen">
            <Sidebar
              isOpen={isSidebarOpen}
              pageListComponent={<PageList pageList={pageListQuery.data} />}
            />

            <EditorPane editorComponent={<NoSSRTiptap />} />
          </div>
        )}
      </main>

      <ReactQueryDevtools initialIsOpen={false} position="bottom-right" />
    </>
  );
}
