import Head from "next/head";
import Image from "next/image";
import clsx from "clsx";
import dynamic from "next/dynamic";
import NoSSR from "react-no-ssr";

import { Inter } from "@next/font/google";
import Tiptap from "../components/Tiptap";

const inter = Inter({ subsets: ["latin"] });

const NoSSRTiptap = dynamic(() => import("../components/Tiptap"), {
  ssr: false,
});

const isServer = () => typeof window === "undefined";

export default function Home() {
  return (
    <>
      <Head>
        <title>Project Potion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(inter.className, "h-full w-full")}>
        <NoSSRTiptap />
        {/* <NoSSR>
          <Tiptap />
        </NoSSR> */}
      </main>
    </>
  );
}
