/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPageRouteImport } from './routes/_auth.page'
import { Route as AuthPageIndexRouteImport } from './routes/_auth.page.index'
import { Route as AuthPagePageIdRouteImport } from './routes/_auth.page.$pageId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPageRoute = AuthPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPageIndexRoute = AuthPageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPageRoute,
} as any)
const AuthPagePageIdRoute = AuthPagePageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AuthPageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/page': typeof AuthPageRouteWithChildren
  '/page/$pageId': typeof AuthPagePageIdRoute
  '/page/': typeof AuthPageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/page/$pageId': typeof AuthPagePageIdRoute
  '/page': typeof AuthPageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/signin': typeof SigninRoute
  '/_auth/page': typeof AuthPageRouteWithChildren
  '/_auth/page/$pageId': typeof AuthPagePageIdRoute
  '/_auth/page/': typeof AuthPageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/page' | '/page/$pageId' | '/page/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/page/$pageId' | '/page'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/signin'
    | '/_auth/page'
    | '/_auth/page/$pageId'
    | '/_auth/page/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/page': {
      id: '/_auth/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof AuthPageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/page/': {
      id: '/_auth/page/'
      path: '/'
      fullPath: '/page/'
      preLoaderRoute: typeof AuthPageIndexRouteImport
      parentRoute: typeof AuthPageRoute
    }
    '/_auth/page/$pageId': {
      id: '/_auth/page/$pageId'
      path: '/$pageId'
      fullPath: '/page/$pageId'
      preLoaderRoute: typeof AuthPagePageIdRouteImport
      parentRoute: typeof AuthPageRoute
    }
  }
}

interface AuthPageRouteChildren {
  AuthPagePageIdRoute: typeof AuthPagePageIdRoute
  AuthPageIndexRoute: typeof AuthPageIndexRoute
}

const AuthPageRouteChildren: AuthPageRouteChildren = {
  AuthPagePageIdRoute: AuthPagePageIdRoute,
  AuthPageIndexRoute: AuthPageIndexRoute,
}

const AuthPageRouteWithChildren = AuthPageRoute._addFileChildren(
  AuthPageRouteChildren,
)

interface AuthRouteChildren {
  AuthPageRoute: typeof AuthPageRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPageRoute: AuthPageRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
